name: Upload (linux)

on: workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Rust
      run: cargo build --release --verbose
    - name: Upload
      uses: actions/upload-artifact@v4.3.3
      with:
        name: WireGuard UI Artifact
        path: target/release/**.exe